### PR TITLE
issue #47 resolved

### PR DESCRIPTION
**Pull request by shubhamkakkar**
`useNativeDriver: true`
added

### CODE REVIEW

**Comment by HiepVu511** [comment]
I think you must change this to `useNativeDriver: false` or you will get this error, just like I did 😄 
Screenshot at Apr 22 13-27-25

**Comment by shubhamkakkar** [comment]
I did not encounter this error, could you share your repo.
We can move height animation to transform animation if required.

**Comment by HiepVu511** [comment]
My project is private right now, but I can share my package.json:
```
{
  "name": "Tproj",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@apollo/react-hooks": "^3.1.3",
    "@graphql-codegen/cli": "^1.13.1",
    "@graphql-codegen/fragment-matcher": "^1.13.1",
    "@react-native-community/masked-view": "^0.1.7",
    "@react-navigation/bottom-tabs": "^5.0.0",
    "@react-navigation/drawer": "^5.5.0",
    "@react-navigation/native": "^5.0.0",
    "@react-navigation/stack": "^5.0.0",
    "@react-navigation/web": "~1.0.0-alpha.9",
    "apollo-cache-inmemory": "^1.6.5",
    "apollo-client": "^2.6.8",
    "apollo-link": "^1.2.13",
    "apollo-link-context": "^1.0.19",
    "apollo-link-error": "^1.1.12",
    "apollo-link-http": "^1.5.16",
    "graphql": "^14.6.0",
    "graphql-tag": "^2.10.3",
    "react": "16.11.0",
    "react-devtools": "^4.6.0",
    "react-dom": "~16.9.0",
    "react-native": "0.62.0",
    "react-native-elements": "^1.2.7",
    "react-native-gesture-handler": "~1.5.0",
    "react-native-numeric-input": "^1.8.3",
    "react-native-reanimated": "~1.4.0",
    "react-native-render-html": "^4.2.0",
    "react-native-safe-area-context": "^0.6.0",
    "react-native-screens": "2.0.0-alpha.12",
    "react-native-snackbar-component": "https://github.com/shubhamkakkar/React-Native-SnackBar-Component.git",
    "react-native-vector-icons": "^6.6.0",
    "react-native-web": "^0.12.2",
    "react-native-webview": "^9.0.2",
    "reanimated-bottom-sheet": "^1.0.0-alpha.19",
    "tipsi-stripe": "^7.5.3"
  },
  "devDependencies": {
    "@babel/core": "^7.6.2",
    "@babel/runtime": "^7.6.2",
    "@react-native-community/eslint-config": "^0.0.5",
    "@types/jest": "^25.2.1",
    "@types/react": "^16.9.32",
    "@types/react-native": "^0.62.1",
    "@types/react-test-renderer": "^16.9.2",
    "babel-jest": "^24.9.0",
    "babel-plugin-import-graphql": "^2.7.0",
    "eslint": "^6.5.1",
    "jest": "^24.9.0",
    "metro-react-native-babel-preset": "^0.58.0",
    "react-test-renderer": "16.11.0",
    "typescript": "^3.8.3"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

**Comment by sidevesh** [comment]
Hey @shubhamkakkar ,
Thanks for the PR!,
I agree with @HiepVu511's reply,
currently setting useNativeDriver to true will result in an error since height doesn't support it.
Maybe we can explore the transform based approach as you mentioned.
Closing this for now.

**Pull request closed without merging**
